/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : number,
}
export interface Reservation {
  'id' : bigint,
  'status' : string,
  'date' : string,
  'createdAt' : bigint,
  'time' : string,
  'guestName' : string,
  'partySize' : bigint,
  'phone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[string, string, string, number], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReservation' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getReservations' : ActorMethod<
    [],
    { 'reservations' : Array<Reservation>, 'completed' : Array<Reservation> }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedMenuItems' : ActorMethod<[], undefined>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, string, number, boolean],
    undefined
  >,
  'updateReservationStatus' : ActorMethod<[bigint, string], [string, bigint]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];